services:
  db:
    image: postgres:17
    container_name: cadet_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_DEV_USER}
      POSTGRES_PASSWORD: ${DB_DEV_PASSWORD}
      POSTGRES_DB: ${DB_DEV_NAME}
    ports:
      - "${DB_DEV_PORT_HOST}:${DB_DEV_PORT_INTERNAL}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data